name: abissiniya
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"







dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.10
  cloud_firestore: ^3.1.15

  flutter_typeahead: ^3.2.4
  flutter_spinkit: ^5.1.0
  provider: ^6.0.2
  google_fonts: ^2.3.1
  form_field_validator: ^1.1.0
  flutter_datetime_picker: ^1.5.1
  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  assets:
    - assets/
    - assets/images/  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
